development:
  dialect: "mysql"
  database: "ceremics_development"
  host: "localhost"
  port: "3306"
  user: "buffalo"
  password: "GoBuffalo"

test:
  url: {{envOr "TEST_DATABASE_URL" "mysql://buffalo:GoBuffalo@(localhost:3306)/ceremics_test?parseTime=true&multiStatements=true&readTimeout=1s"}}

production:
  url: {{envOr "DATABASE_URL" "mysql://buffalo:GoBuffalo@(localhost:3306)/ceremics_production?parseTime=true&multiStatements=true&readTimeout=1s"}}